from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class CuratedStation:
    id: str
    display_name: str
    water_system: str
    station_group: str
    station_group_label: str
    significance: str
    sort_order: int


CURATED_STATIONS: tuple[CuratedStation, ...] = (
    CuratedStation(
        "lobith.bovenrijn.tolkamer",
        "Lobith",
        "Rhine",
        "rhine",
        "Rhine",
        "Total Rhine inflow entering the Netherlands",
        1,
    ),
    CuratedStation(
        "maastricht.borgharen.maas.beneden",
        "Borgharen-Dorp",
        "Maas",
        "meuse",
        "Meuse",
        "Maas water level immediately downstream of Belgium",
        2,
    ),
    CuratedStation(
        "hoekvanholland",
        "Hoek van Holland",
        "North Sea/Rijnmond",
        "coastal",
        "Coastal",
        "Storm surge, tide and Rhine-Meuse delta boundary",
        3,
    ),
    CuratedStation(
        "vlissingen",
        "Vlissingen",
        "Western Scheldt",
        "southwest_delta",
        "Southwest Delta",
        "Scheldt estuary tides and coastal storm surge",
        4,
    ),
    CuratedStation(
        "ijmuiden.buitenhaven",
        "IJmuiden",
        "North Sea/Noordzeekanaal",
        "coastal",
        "Coastal",
        "Central coast and Noordzeekanaal entrance",
        5,
    ),
    CuratedStation(
        "delfzijl",
        "Delfzijl",
        "Ems estuary",
        "coastal",
        "Coastal",
        "Northeastern coastal flood risk",
        6,
    ),
    CuratedStation(
        "denhelder.marsdiep",
        "Den Helder",
        "North Sea/Wadden Sea",
        "coastal",
        "Coastal",
        "North Sea-Wadden Sea exchange",
        7,
    ),
    CuratedStation(
        "harlingen.waddenzee",
        "Harlingen",
        "Wadden Sea",
        "coastal",
        "Coastal",
        "Central Wadden Sea and Frisian coast",
        8,
    ),
    CuratedStation(
        "pannerden.regelwerk.boven",
        "Pannerden - regelwerk boven",
        "Rhine distributaries",
        "rhine",
        "Rhine",
        "Rhine-water distribution toward Waal and Pannerdensch Kanaal",
        9,
    ),
    CuratedStation(
        "westervoort.ijsselkop",
        "IJsselkop",
        "IJssel/Nederrijn",
        "rhine",
        "Rhine",
        "Distribution between IJssel and Nederrijn",
        10,
    ),
    CuratedStation(
        "nijmegen.waal",
        "Nijmegen-Haven",
        "Waal",
        "rhine",
        "Rhine",
        "Upper Waal level and navigation conditions",
        11,
    ),
    CuratedStation(
        "tiel.waal",
        "Tiel-Waal",
        "Waal",
        "rhine",
        "Rhine",
        "Middle Waal; useful propagation point downstream of Nijmegen",
        12,
    ),
    CuratedStation(
        "dordrecht.oudemaas.benedenmerwede",
        "Dordrecht",
        "Beneden-Merwede/Oude Maas",
        "southwest_delta",
        "Southwest Delta",
        "River discharge combined with tidal influence",
        13,
    ),
    CuratedStation(
        "westervoort.hondsbroekschepleij.ijssel",
        "Hondsbroeksche Pleij-IJssel",
        "IJssel",
        "ijssel",
        "IJssel",
        "Upper IJssel after the main Rhine bifurcation",
        14,
    ),
    CuratedStation(
        "zwolle.ijssel",
        "Katerveer",
        "IJssel",
        "ijssel",
        "IJssel",
        "Lower IJssel before it reaches the IJsselmeer",
        15,
    ),
    CuratedStation(
        "roermond.boven",
        "Roermond-boven",
        "Maas",
        "meuse",
        "Meuse",
        "Central Limburg and Roer-Maas system",
        16,
    ),
    CuratedStation(
        "venlo",
        "Venlo",
        "Maas",
        "meuse",
        "Meuse",
        "Northern Limburg; important high-water reference",
        17,
    ),
    CuratedStation(
        "grave.beneden",
        "Grave-beneden",
        "Maas",
        "meuse",
        "Meuse",
        "Lower, heavily regulated Maas",
        18,
    ),
    CuratedStation(
        "lith.beneden",
        "Lith-Dorp",
        "Maas",
        "meuse",
        "Meuse",
        "Final regulated reach before the lower-river area",
        19,
    ),
    CuratedStation(
        "rotterdam.nieuwemaas.boerengat",
        "Rotterdam - Nieuwe Maas/Boerengat",
        "Rijnmond",
        "rhine",
        "Rhine",
        "Urban Rotterdam and tidal penetration inland",
        20,
    ),
    CuratedStation(
        "moerdijk",
        "Moerdijk",
        "Hollandsch Diep",
        "southwest_delta",
        "Southwest Delta",
        "Connection between river discharge and southwest delta",
        21,
    ),
    CuratedStation(
        "hellevoetsluis",
        "Hellevoetsluis",
        "Haringvliet",
        "southwest_delta",
        "Southwest Delta",
        "Haringvliet control, tides and delta water management",
        22,
    ),
    CuratedStation(
        "denoever.ijsselmeer.binnenhaven",
        "Den Oever-binnen",
        "IJsselmeer",
        "lakes",
        "Lakes",
        "IJsselmeer level at the Afsluitdijk",
        23,
    ),
    CuratedStation(
        "lemmer.ijsselmeer",
        "Lemmer",
        "IJsselmeer",
        "lakes",
        "Lakes",
        "Eastern IJsselmeer and freshwater management",
        24,
    ),
    CuratedStation(
        "lelystad.houtribsluis.noord",
        "Lelystad-Haven",
        "Markermeer",
        "lakes",
        "Lakes",
        "Markermeer level and wind-induced setup",
        25,
    ),
)

CURATED_STATION_BY_ID = {station.id: station for station in CURATED_STATIONS}
CURATED_STATION_IDS = frozenset(CURATED_STATION_BY_ID)
